name: analytics

on: push

jobs:
  analytics:
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: checkout
        uses: actions/checkout@v1

      - name: build and test
        run: |
          cd $GITHUB_WORKSPACE && go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov

      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.23.8
          GO111MODULE=off go get -u -v github.com/mattn/goveralls

      - name: run linters
        run: cd $GITHUB_WORKSPACE && $GITHUB_WORKSPACE/golangci-lint run --modules-download-mode=readonly

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build image
        run: docker build --build-arg VERSION=$GITHUB_REF:$GITHUB_SHA -t $GITHUB_REPOSITORY .

      - name: publish image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_DOCKER_TOKEN }}
          docker push $GITHUB_REPOSITORY
